name: Check Formatting

on:
  pull_request:
    branches: [master]

jobs:
  check-formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Unit Tests
        uses: cclauss/GitHub-Action-for-pytest@0.5.0
