name: microk8s-puppetmaster
base: core20
version: git
summary: MicroK8s Cloud Puppermaster
description: |
  Listen for cloud events and drive MicroK8s accordingly.

grade: stable
confinement: classic

apps:
  microk8s-puppetmaster:
    daemon: simple
    command: bin/python3 $SNAP/bin/puppetmaster

parts:
  microk8s-puppetmaster:
    plugin: python
    python-packages:
      - wheel
    source: .
