name: microk8s-puppetmaster
base: core20
version: git
summary: Autoscale cloud appliances
description: |
  Listen for cloud events and drive MicroK8s accordingly.

grade: stable
confinement: classic

apps:
  microk8s-puppetmaster:
    daemon: simple
    command: bin/python3 $SNAP/bin/autoscale

parts:
  microk8s-puppetmaster:
    plugin: python
    python-packages:
      - wheel
    source: .
