name: joule-expansion
base: core20
version: git
summary: Automate the scaling of applications inside cloud scale groups.
description: |
  Allow applications, running inside cloud scale groups, to have a say in how and when
  they're scaled.

grade: stable
confinement: classic

apps:
  joule:
    daemon: simple
    command: bin/python3 $SNAP/bin/joule

parts:
  joule:
    plugin: python
    python-packages:
      - wheel
    source: .
