name: joule-expansion
base: core20
version: git
summary: Automate the scaling of applications inside cloud scale groups.
description: |
  Allow applications, running inside cloud scale groups, to have a say in how and when
  they're scaled.

grade: stable
confinement: classic

apps:
  joule-expansion:
    daemon: simple
    restart-condition: always
    command: wrapper.sh

parts:
  wrapper:
    plugin: dump
    source: ./snap/local/bin
    stage:
      - wrapper.sh
  joule-expansion:
    plugin: python
    stage-packages:
      - libpython3-stdlib
      - libpython3.8-stdlib
      - libpython3.8-minimal
      - python3-pip
      - python3-setuptools
      - python3-wheel
      - python3-venv
      - python3-minimal
      - python3-distutils
      - python3-pkg-resources
      - python3.8-minimal
    source: .

