name: joule-expansion
base: core20
version: git
summary: Automate the scaling of applications inside cloud scale groups.
description: |
  Allow applications, running inside cloud scale groups, to have a say in how and when
  they're scaled.

grade: stable
confinement: classic

apps:
  joule-expansion:
    daemon: simple
    command: wrapper.sh

parts:
  wrapper:
    plugin: dump
    source: ./snap/local/bin
    stage:
      - wrapper.sh
  joule-expansion:
    plugin: python
    python-packages:
      - wheel
    source: .
