name: Check Formatting
on:
  pull_request:
    branches: [master]
jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Black Python Formatting
        uses: jpetrucciani/black-check@20.8b1
        with:
          path: "./joule"
  typing:
    runs-on: ubuntu-latest
    steps:
      - uses: jpetrucciani/mypy-check@master
      - name: MyPy Typing Check
        with:
          path: "./joule"
