name: Check Formatting

on:
  pull_request:
    branches: [main]

jobs:
  check-formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Requirements
        run: |
          pip install -r tests/requirements.txt
      - name: Black Python Formatting
        uses: jpetrucciani/black-check@20.8b1
        with:
          path: "./joule"
      - name: MyPy Typing Check
        uses: jpetrucciani/mypy-check@master
        with:
          path: "./joule"
