name: Check Formatting

on:
  pull_request:
    branches: [main]

jobs:
  check-formatting:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Requirements
        run: |
          pip install -r tests/requirements.txt
      - name: Black Python Formatting
        uses: psf/black@stable
        with:
          src: "./joule"
      - name: MyPy Typing Check
        uses: jpetrucciani/mypy-check@0.971
        with:
          path: "./joule"
