name: Check Formatting

on:
  pull_request:
    branches: [master]

jobs:
  check-formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Black Python Formatting
        uses: jpetrucciani/black-check@20.8b1
        with:
          path: "./joule"
      - name: MyPy Typing Check
        uses: jpetrucciani/mypy-check@master
        with:
          path: "./joule"
